name: $(Build.SourceBranchName)-$(Rev:.r)

trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

resources:
  containers:
  - container: u18
    image: williamfgc/adios2-2.5.0-py3:ubuntu18.04

jobs:
- job: RunInContainer
  timeoutInMinutes: 5
  
  pool:
    vmImage: 'ubuntu-18.04'

  strategy:
    matrix:
      ubuntu18:
        containerResource: u18

  container: $[ variables['containerResource'] ]
  
  steps:
    - bash: scripts/ci/azure/build.sh
      name: Init
      